name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
# Add environment variable if you have one to avoid errors with reading secrets
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: a0d921d42eaf55485d6881f8ce06ad15
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
